### ISSUE TITLE
We should have a SIG Testing triage party instance

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/sig-testing#7]
I know some other SIGs have experiment with this for issue triage. I think most triage right now is myself + @spiffxp, we should really be scaling that more.

cc @dims @ameukam 

xref discussions about issue triage https://github.com/kubernetes/kubernetes/issues/103151

we should also consider working on making it easier to stamp out instances for SIGs: https://twitter.com/BenTheElder/status/1407851591319703552 🧵 

I think the biggest question is what token to run it on.

see also: https://twitter.com/thomrstrom/status/1408152928926502919

**Comment by spiffxp** [comment]
/remove-lifecycle stale
We noted during yesterday's SIG K8s Infra meeting that release and cli are sharing the same token, I think we could do the same

/sig testing
/sig k8s-infra

**Comment by ameukam** [comment]
> /remove-lifecycle stale
> We noted during yesterday's SIG K8s Infra meeting that release and cli are sharing the same token, I think we could do the same
> 
> /sig testing
> /sig k8s-infra

Also take a look at the new GitHub feature : https://github.blog/changelog/2021-09-29-the-new-github-issues-09-29-update/

**Comment by BenTheElder** [comment]
In the current state I'm not sure many people would look through this anyhow :/

I look through the assorted repos just using GitHub when I can. When they are multi sig repos I check for issues tagged with the SIG using GitHub search. It works OK and doesn't require us to maintain yet another deployment.

I think this is something we should do in the future if we're better staffed and more active again.
